### ISSUE TITLE
suggestions on title

### ISSUE THREAD

**Issue by courtney-rosenthal** [mateoclarke/311vs10One#20]
I suggest a page title: "311 vs 10-ONE District Map"

"Open311" refers to a particular API, which isn't being used in this demo. I'd recommend calling it just "311".

"10-ONE" is the branding that the city uses for the new council district map.

http://www.austintexas.gov/department/10-one

**Comment by mateoclarke** [comment]
This suggestion has been merged into the gh-pages branch
